### PR TITLE
Animation compatibility with DrizztSaga for EE (Red Harpy animation slot)

### PR DESCRIPTION
**Pull request by Roberciiik**

### CODE REVIEW

**Comment by GraionDilach** [comment]
Care to explain this one?

What is the animation supposed to be used here? Harpy is 0xE252, and should be useable in the EEs, at worst one needs to bring the BAMs and audio over from IWDEE. AFAIK HALFDRAGON_RED is also missing from BG2EE (it is included in SoD).

**Comment by Roberciiik** [comment]
Sure, the Region of Terror installs Red Harpy (a.k.a. Halfdragon) animation at HARPY slot on EE games. This makes incompatibility with DrizztSaga that checks if the MHAR slot is used, to not install the same animation twice. However, it causes that DrizztSaga has Halfdragon red harpies instead of normal harpies. So my change switches the incorrect MHAR slot to correct MDH2 (is Halfdragon slot) for EE games only.

**Comment by GraionDilach** [comment]
Ahh, this isn't a compatibility issue but an outright fix then. When it comes to cases like this, I tend to look at the WIP IAv6 animation reference chart from Gwendolyne's local repository.

**Review by GraionDilach — APPROVED** [review]

**Comment by Roberciiik** [comment]
It is a proper fix AND compatibility fix for overrode animation in the other mod.

**Pull request merged**
